version: 0.2

phases:
  install:
    commands:
    - echo $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    - curl -s $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    - SQSProducer $SQS_COMMAND_QUEUE_URL $SQS_RESPONSE_QUEUE_URL code/cli-build/codebuild-install.sh

  pre_build:
    commands:
      - SQSProducer $SQS_COMMAND_QUEUE_URL $SQS_RESPONSE_QUEUE_URL code/cli-build/codebuild-pre-build.sh
  
  build:
    commands:
      - SQSProducer $SQS_COMMAND_QUEUE_URL $SQS_RESPONSE_QUEUE_URL code/cli-build/codebuild-build.sh

  post_build:
    commands:
      - SQSProducer $SQS_COMMAND_QUEUE_URL $SQS_RESPONSE_QUEUE_URL code/cli-build/codebuild-post-build.sh
